name: Build APK

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build APK
        working-directory: ./client
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: client/bin/*.apk
